[package]
description       = "rspack split chunks plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_split_chunks"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap            = { workspace = true }
derive_more        = { workspace = true, features = ["debug"] }
futures            = { workspace = true }
itertools          = { workspace = true }
rayon              = { workspace = true }
regex              = { workspace = true }
rspack_collections = { workspace = true }
rspack_core        = { workspace = true }
rspack_error       = { workspace = true }
rspack_futures     = { workspace = true }
rspack_hash        = { workspace = true }
rspack_hook        = { workspace = true }
rspack_regex       = { workspace = true }
rspack_util        = { workspace = true }
rustc-hash         = { workspace = true }
tracing            = { workspace = true }
