
[package]
description = "rspack macros plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_napi_macros"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote       = { workspace = true }
syn         = { workspace = true, features = ["full"] }
