[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_futures"
repository = "https://github.com/web-infra-dev/rspack"
version    = "0.1.0"


[dependencies]
async-scoped = { workspace = true, features = ["use-tokio"] }
