[package]
description = "rspack futures"
edition     = "2021"
license     = "MIT"
name        = "rspack_futures"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
[dependencies]
tokio = { version = "1", features = ["rt"] }
[target.'cfg(target_family = "wasm")'.dependencies]
futures = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-scoped = { workspace = true, features = ["use-tokio"] }
