[package]
description       = "rspack futures"
edition.workspace = true
license           = "MIT"
name              = "rspack_futures"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[dependencies]
rspack_tasks = { workspace = true }
tokio        = { workspace = true, features = ["rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
