[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_plugin_progress"
repository = "https://github.com/web-infra-dev/rspack"
version    = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait     = { workspace = true }
indicatif       = "0.17.8"
linked-hash-map = "0.5.6"
rspack_core     = { path = "../rspack_core" }
rspack_error    = { path = "../rspack_error" }
rspack_hook     = { path = "../rspack_hook" }
tracing         = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
