[package]
description       = "rspack runtime plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_runtime"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait              = { workspace = true }
atomic_refcell           = { workspace = true }
cow-utils                = { workspace = true }
derive_more              = { workspace = true, features = ["debug"] }
futures                  = { workspace = true }
indexmap                 = { workspace = true }
itertools                = { workspace = true }
rspack_cacheable         = { workspace = true }
rspack_collections       = { workspace = true }
rspack_core              = { workspace = true }
rspack_error             = { workspace = true }
rspack_hash              = { workspace = true }
rspack_hook              = { workspace = true }
rspack_plugin_javascript = { workspace = true }
rspack_util              = { workspace = true }
swc_core                 = { workspace = true, features = ["common", "ecma_ast", "ecma_parser"] }
tokio                    = { workspace = true }

rustc-hash = { workspace = true }
serde_json = { workspace = true }
tracing    = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing", "tokio"]

[lints.rust.unexpected_cfgs]
check-cfg = ['cfg(allocative)']
level     = "warn"
