[package]
description = "rspack runtime plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_runtime"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait              = { workspace = true }
cow-utils                = { workspace = true }
dashmap                  = { workspace = true }
derive_more              = { workspace = true, features = ["debug"] }
indexmap                 = { workspace = true }
itertools                = { workspace = true }
pollster                 = { workspace = true }
rspack_cacheable         = { workspace = true }
rspack_collections       = { workspace = true }
rspack_core              = { workspace = true }
rspack_error             = { workspace = true }
rspack_hash              = { workspace = true }
rspack_hook              = { workspace = true }
rspack_plugin_javascript = { workspace = true }
rspack_util              = { workspace = true }
tokio                    = { workspace = true }

rustc-hash = { workspace = true }
serde_json = { workspace = true }
tracing    = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
