[package]
description       = "rspack paths"
edition.workspace = true
license           = "MIT"
name              = "rspack_paths"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino           = { workspace = true }
dashmap          = { workspace = true }
indexmap         = { workspace = true }
rspack_cacheable = { workspace = true }
rustc-hash       = { workspace = true }
ustr             = { workspace = true }
