[package]
authors.workspace       = true
categories.workspace    = true
description             = "Rspack javascript compiler"
documentation.workspace = true
edition.workspace       = true
homepage.workspace      = true
license.workspace       = true
name                    = "rspack_javascript_compiler"
repository.workspace    = true
version.workspace       = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
indoc = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
swc_config = { workspace = true }
swc_core = { workspace = true, features = [
  "__ecma",
  "__visit",
  "__utils",
  "__ecma_transforms",
  "__parser",
  "ecma_ast",
  "ecma_codegen",
  "ecma_quote",
  "common_concurrent",
  "swc_ecma_ast",
  "ecma_transforms_react",
  "ecma_transforms_module",
  "ecma_parser_unstable",
  "swc_ecma_codegen",
  "swc_ecma_visit",
] }
swc_ecma_minifier = { workspace = true, features = ["concurrent"] }
swc_error_reporters = { workspace = true }
swc_node_comments = { workspace = true }
url = { workspace = true }

rspack_error     = { workspace = true }
rspack_sources   = { workspace = true }
rspack_util      = { workspace = true }
rspack_workspace = { workspace = true }

[lints]
workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
stacker = { workspace = true }
