[package]
description = "rspack json plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_json"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cow-utils        = { workspace = true }
json             = { workspace = true }
ropey            = "1.6.1"
rspack_cacheable = { workspace = true }
rspack_core      = { workspace = true }
rspack_error     = { workspace = true }
rspack_util      = { workspace = true }
