[package]
description       = "rspack json plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_json"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait      = { workspace = true }
cow-utils        = { workspace = true }
json             = { workspace = true }
rspack_cacheable = { workspace = true }
rspack_core      = { workspace = true }
rspack_error     = { workspace = true }
rspack_util      = { workspace = true }

[lints]
workspace = true
