[package]
edition = "2021"
name = "rspack_plugin_json"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev_dependencies]
temp_test_utils = { path = "../temp_test_utils" }
testing_macros = "0.2.5"

[dependencies]
rspack_core = { path = "../rspack_core" }
tracing = "0.1.34"
anyhow = "1"
hashbrown = "0.12.1"
json = "0.12.4"
