[package]
edition = "2021"
name = "rspack_test"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
derive_builder = "0.11.2"
node_binding = { path = "../node_binding", package = "rspack_node", features = [
  "test",
] }
rayon = "1.5.3"
rspack = { path = "../rspack" }
rspack_core = { path = "../rspack_core" }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
similar = "2.1.0"
testing_macros = "0.2.5"
tokio = "1.20.1"
