[package]
description       = "rspack cache storage"
edition.workspace = true
license           = "MIT"
name              = "rspack_storage"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait  = { workspace = true }
cow-utils    = { workspace = true }
futures      = { workspace = true }
itertools    = { workspace = true }
rayon        = { workspace = true }
rspack_error = { workspace = true }
rspack_fs    = { workspace = true }
rspack_paths = { workspace = true }
rspack_util  = { workspace = true }
rustc-hash   = { workspace = true }
tokio        = { workspace = true, features = ["time"] }
tracing      = { workspace = true }

[dev-dependencies]
