[package]
description = "rspack cache storage"
edition     = "2021"
license     = "MIT"
name        = "rspack_storage"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait  = { workspace = true }
cow-utils    = { workspace = true }
futures      = { workspace = true }
itertools    = { workspace = true }
pollster     = { workspace = true }
rayon        = { workspace = true }
rspack_error = { workspace = true }
rspack_fs    = { workspace = true }
rspack_paths = { workspace = true }
rustc-hash   = { workspace = true }
tokio        = { workspace = true }
tracing      = { workspace = true }

[dev-dependencies]
