[package]
description       = "rspack plugin worker"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_worker"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspack_core  = { workspace = true }
rspack_error = { workspace = true }
rspack_hook  = { workspace = true }
tracing      = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]

[lints]
workspace = true
