[package]
description       = "rspack banner plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_banner"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cow-utils    = { workspace = true }
futures      = { workspace = true }
regex        = { workspace = true }
rspack_core  = { workspace = true }
rspack_error = { workspace = true }
rspack_hook  = { workspace = true }
rspack_util  = { workspace = true }
tracing      = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]

[lints]
workspace = true
