[package]
description = "rspack fs node"
edition     = "2021"
license     = "MIT"
name        = "rspack_fs_node"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
async-trait  = { workspace = true }
futures      = { workspace = true }
napi         = { workspace = true, features = ["napi4", "tokio_rt"] }
napi-derive  = { workspace = true }
rspack_error = { workspace = true }
rspack_fs    = { workspace = true }
rspack_napi  = { workspace = true }
rspack_paths = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(node)'] }
