[package]
description = "rspack context replacement plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_context_replacement"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.1.0"

[dependencies]
derivative     = { workspace = true }
rspack_core    = { version = "0.1.0", path = "../rspack_core" }
rspack_error   = { version = "0.1.0", path = "../rspack_error" }
rspack_hook    = { version = "0.1.0", path = "../rspack_hook" }
rspack_paths   = { version = "0.1.0", path = "../rspack_paths" }
rspack_regex   = { version = "0.1.0", path = "../rspack_regex" }
tracing        = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
