[package]
description       = "rspack externals plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_externals"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex                    = { workspace = true }
rspack_core              = { workspace = true }
rspack_error             = { workspace = true }
rspack_hook              = { workspace = true }
rspack_plugin_javascript = { workspace = true }
rspack_regex             = { workspace = true }
tracing                  = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]

[lints]
workspace = true
