[package]
description             = "rspack lazy compilation plugin"
documentation.workspace = true
edition                 = "2021"
homepage.workspace      = true
license                 = "MIT"
name                    = "rspack_plugin_lazy_compilation"
repository.workspace    = true
version                 = "0.2.0"

[dependencies]
async-trait = { workspace = true }
cow-utils   = { workspace = true }
rustc-hash  = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }

rspack_cacheable         = { workspace = true }
rspack_collections       = { workspace = true }
rspack_core              = { workspace = true }
rspack_error             = { workspace = true }
rspack_hook              = { workspace = true }
rspack_plugin_javascript = { workspace = true }
rspack_regex             = { workspace = true }
rspack_util              = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
