[package]
edition = "2021"
license = "MIT"
name    = "rspack_plugin_lazy_compilation"
version = "0.1.0"
description = "rspack lazy compilation plugin"
[dependencies]
async-trait = { workspace = true }
rustc-hash  = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }

rspack_collections       = { path = "../rspack_collections" }
rspack_core              = { path = "../rspack_core" }
rspack_error             = { path = "../rspack_error" }
rspack_hook              = { path = "../rspack_hook" }
rspack_plugin_javascript = { path = "../rspack_plugin_javascript" }
rspack_regex             = { path = "../rspack_regex" }
rspack_util              = { path = "../rspack_util" }

[package.metadata.cargo-shear]
ignored = ["tracing"]
