[package]
description             = "rspack lazy compilation plugin"
documentation.workspace = true
edition.workspace       = true
homepage.workspace      = true
license                 = "MIT"
name                    = "rspack_plugin_lazy_compilation"
repository.workspace    = true
version.workspace       = true

[dependencies]
async-trait = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }

rspack_cacheable         = { workspace = true }
rspack_collections       = { workspace = true }
rspack_core              = { workspace = true }
rspack_error             = { workspace = true }
rspack_hash              = { workspace = true }
rspack_hook              = { workspace = true }
rspack_paths             = { workspace = true }
rspack_plugin_javascript = { workspace = true }
rspack_regex             = { workspace = true }
rspack_util              = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]

[lints]
workspace = true
