[package]
description             = "rspack lazy compilation plugin"
documentation.workspace = true
edition                 = "2021"
homepage.workspace      = true
license                 = "MIT"
name                    = "rspack_plugin_lazy_compilation"
repository.workspace    = true
version                 = "0.1.0"

[dependencies]
async-trait = { workspace = true }
rustc-hash  = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }

rspack_collections       = { version = "0.1.0", path = "../rspack_collections" }
rspack_core              = { version = "0.1.0", path = "../rspack_core" }
rspack_error             = { version = "0.1.0", path = "../rspack_error" }
rspack_hook              = { version = "0.1.0", path = "../rspack_hook" }
rspack_plugin_javascript = { version = "0.1.0", path = "../rspack_plugin_javascript" }
rspack_regex             = { version = "0.1.0", path = "../rspack_regex" }
rspack_util              = { version = "0.1.0", path = "../rspack_util" }

[package.metadata.cargo-shear]
ignored = ["tracing"]
