[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_allocator"
repository = "https://github.com/web-infra-dev/rspack"
version    = "0.1.0"
description = "rspack allocator"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "linux")'.dependencies]
# Turned on `local_dynamic_tls` to avoid issue: https://github.com/microsoft/mimalloc/issues/147
mimalloc = { workspace = true, features = ["local_dynamic_tls"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
mimalloc = { workspace = true }
