[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_testing"
repository = "https://github.com/web-infra-dev/rspack"
version    = "0.1.0"

[[bin]]
bench = false
name  = "gen_test_config_schema"
path  = "./bin/gen_test_config_schema.rs"
test  = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspack_binding_options               = { path = "../rspack_binding_options" }
rspack_core                          = { path = "../rspack_core" }
rspack_error                         = { path = "../rspack_error" }
rspack_fs                            = { path = "../rspack_fs", features = ["async", "rspack-error"] }
rspack_ids                           = { path = "../rspack_ids" }
rspack_loader_swc                    = { path = "../rspack_loader_swc" }
rspack_plugin_asset                  = { path = "../rspack_plugin_asset" }
rspack_plugin_css                    = { path = "../rspack_plugin_css" }
rspack_plugin_devtool                = { path = "../rspack_plugin_devtool" }
rspack_plugin_entry                  = { path = "../rspack_plugin_entry" }
rspack_plugin_externals              = { path = "../rspack_plugin_externals" }
rspack_plugin_hmr                    = { path = "../rspack_plugin_hmr" }
rspack_plugin_html                   = { path = "../rspack_plugin_html", features = ["testing"] }
rspack_plugin_javascript             = { path = "../rspack_plugin_javascript" }
rspack_plugin_json                   = { path = "../rspack_plugin_json" }
rspack_plugin_merge_duplicate_chunks = { path = "../rspack_plugin_merge_duplicate_chunks" }
rspack_plugin_remove_empty_chunks    = { path = "../rspack_plugin_remove_empty_chunks" }
rspack_plugin_runtime                = { path = "../rspack_plugin_runtime" }
rspack_plugin_warn_sensitive_module  = { path = "../rspack_plugin_warn_sensitive_module" }
rspack_plugin_wasm                   = { path = "../rspack_plugin_wasm" }
rspack_regex                         = { path = "../rspack_regex" }
rspack_tracing                       = { path = "../rspack_tracing" }
rspack_util                          = { path = "../rspack_util" }

async-trait    = { workspace = true }
cargo-rst      = { path = "../cargo-rst" }
schemars       = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
swc_core       = { workspace = true }
testing_macros = { workspace = true, features = [] }
tokio          = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "test-util", "parking_lot"] }

insta     = { workspace = true, features = ["json"] }
itertools = { workspace = true }
