[package]
description       = "rspack css plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_css"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
[dependencies]
async-trait           = { workspace = true }
atomic_refcell        = { workspace = true }
cow-utils             = { workspace = true }
css-module-lexer      = { workspace = true }
heck                  = { workspace = true }
indexmap              = { workspace = true }
once_cell             = { workspace = true }
regex                 = { workspace = true }
rspack_cacheable      = { workspace = true }
rspack_collections    = { workspace = true }
rspack_core           = { workspace = true }
rspack_error          = { workspace = true }
rspack_futures        = { workspace = true }
rspack_hash           = { workspace = true }
rspack_hook           = { workspace = true }
rspack_plugin_runtime = { workspace = true }
rspack_util           = { workspace = true }
rustc-hash            = { workspace = true }
serde_json            = { workspace = true }
tokio                 = { workspace = true }
tracing               = { workspace = true }
urlencoding           = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tokio"]

[lints]
workspace = true
