[package]
edition = "2021"
name    = "rspack_plugin_css"
version = "0.1.0"

[dev-dependencies]
insta       = "1.19.1"
rspack      = { path = "../rspack" }
rspack_test = { path = "../rspack_test" }

[dependencies]
anyhow = "1"
async-trait = "0.1.53"
better_scoped_tls = "0.1.0"
bitflags = "1.3.2"
dashmap = "5.0.0"
hashbrown = { version = "0.12.3", features = ["rayon"] }
heck = "0.4.0"
hrx-parser = "0.1.1"
indexmap = "1.9.2"
itertools = "0.10.1"
linked_hash_set = "0.1.4"
once_cell = "1"
preset_env_base = { workspace = true }
rayon = "1.5.3"
regex = "1.6.0"
rspack_core = { path = "../rspack_core" }
rspack_error = { path = "../rspack_error" }
serde = "1.0.144"
serde_json = "1.0.85"
sugar_path = "0.0.9"
swc_core = { workspace = true, features = [
  "css_ast",
  "css_codegen",
  "css_parser",
  "css_utils",
  "css_visit",
  "css_visit_path",
  "css_compat",
  "css_modules",
  "css_prefixer",
  "css_minifier",
] }
tokio = { workspace = true }
tracing = "0.1.34"
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }
