[package]
name = "rspack_plugin_css"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev_dependencies]
node_binding = { path = "../node_binding", package = "rspack_node", features = ["test"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rspack = { path = "../rspack"}
glob = "0.3.0"

[dependencies]
rspack_core = { path = "../rspack_core"}
swc_css = "0.106.0"
tracing = "0.1.34"
once_cell = "1"
linked_hash_set = "0.1.4"
anyhow = "1"
typemap = "0.3.3"
better_scoped_tls = "0.1.0"
rayon = "1.5.3"
tokio = { version = "1.17.0", features = ["full"] }

# swc_atoms = "0.2.11"
# swc_ecma_ast = "0.78.0"
# swc_ecma_codegen = "0.108.1"
# swc_ecma_parser = "0.104.0"
# swc_ecma_visit = "0.64.0"
swc_common = "0.18.3"
# swc_ecma_transforms_base = "0.85.0"
# swc_ecma_transforms_module = "0.112.1"
# swc_ecma_utils = "0.85.0"
# swc_ecma_transforms_react = "0.114.0"
# swc_ecma_transforms_optimization = "0.123.1"
