[package]
name = "rspack_plugin_css"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rspack = { path = "../rspack" }
rspack_test = { path = "../rspack_test" }
insta = "1.19.1"

[dependencies]
rspack_core = { path = "../rspack_core" }
swc_css = "0.125.5"
swc_css_prefixer = "0.123.2"
swc_atoms = "0.4.1"
swc_common = { version = "0.28.3", features = ["concurrent"] }
tracing = "0.1.34"
once_cell = "1"
linked_hash_set = "0.1.4"
anyhow = "1"
# typemap = "0.3.3"
better_scoped_tls = "0.1.0"
rayon = "1.5.3"
tokio = { version = "1.17.0", features = ["full"] }
dashmap = "5.0.0"
sugar_path = "0.0.5"
hashbrown = { version = "0.12.1", features = ["rayon"] }
rspack_error = { path = "../rspack_error" }
preset_env_base = "0.3.1"
hrx-parser = "0.1.1"
regex = "1.6.0"
serde_json = "1.0.85"
serde = "1.0.144"

[profile.release]
debug = true
