[package]
description = "rspack lightingcss loader"
edition     = "2021"
license     = "MIT"
name        = "rspack_loader_lightningcss"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait          = { workspace = true }
derive_more          = { workspace = true, features = ["debug"] }
lightningcss         = { workspace = true, features = ["sourcemap", "browserslist", "visitor", "into_owned"] }
parcel_sourcemap     = { workspace = true }
rspack_cacheable     = { workspace = true }
rspack_core          = { workspace = true }
rspack_error         = { workspace = true }
rspack_hook          = { workspace = true }
rspack_loader_runner = { workspace = true }
serde                = { workspace = true, features = ["derive"] }
serde_json           = { workspace = true }
tokio                = { workspace = true }
