[package]
description = "rspack sensitive module plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_warn_sensitive_module"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"

[dependencies]
cow-utils          = { workspace = true }
rspack_collections = { version = "0.2.0", path = "../rspack_collections" }
rspack_core        = { version = "0.2.0", path = "../rspack_core" }
rspack_error       = { version = "0.2.0", path = "../rspack_error" }
rspack_hook        = { version = "0.2.0", path = "../rspack_hook" }
rustc-hash         = { workspace = true }
tracing            = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
