[package]
name = "rspack_plugin_mock_buitins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspack_core = { path = "../rspack_core" }
nodejs-resolver="0.0.12"
async-trait = "0.1.53"