[package]
description             = "rspack library plugin"
documentation.workspace = true
edition                 = "2021"
homepage.workspace      = true
license                 = "MIT"
name                    = "rspack_plugin_library"
repository.workspace    = true
version                 = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait              = { workspace = true }
regex                    = { workspace = true }
rspack_collections       = { version = "0.1.0", path = "../rspack_collections" }
rspack_core              = { version = "0.1.0", path = "../rspack_core" }
rspack_error             = { version = "0.1.0", path = "../rspack_error" }
rspack_hash              = { version = "0.1.0", path = "../rspack_hash" }
rspack_hook              = { version = "0.1.0", path = "../rspack_hook" }
rspack_plugin_javascript = { version = "0.1.0", path = "../rspack_plugin_javascript" }
rspack_util              = { version = "0.1.0", path = "../rspack_util" }
rustc-hash               = { workspace = true }
serde_json               = { workspace = true }
tracing                  = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
