[package]
description       = "rspack napi"
edition.workspace = true
license           = "MIT"
name              = "rspack_napi"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
browser = ["dep:rspack_browser"]

[dependencies]
napi           = { workspace = true, features = ["async", "tokio_rt", "serde-json", "anyhow", "napi7", "compat-mode"] }
oneshot        = { workspace = true }
rspack_browser = { workspace = true, optional = true }
rspack_error   = { workspace = true }
serde_json     = { workspace = true }
tokio          = { workspace = true, features = ["sync"] }

[lints]
workspace = true
