[package]
description       = "rspack size limits plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_size_limits"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more    = { workspace = true, features = ["debug"] }
futures        = { workspace = true }
rspack_core    = { workspace = true }
rspack_error   = { workspace = true }
rspack_futures = { workspace = true }
rspack_hook    = { workspace = true }
rspack_util    = { workspace = true }
tracing        = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]

[lints]
workspace = true
