[package]
edition = "2021"
name = "rspack_loader_runner"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev_dependencies]
url = "2.2.2"
similar-asserts = "1.2.0"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
async-trait = "0.1.53"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.34"
rspack_sources = { git = "https://github.com/speedy-js/rspack-sources.git", branch = "fix-source" }
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
rspack_error = { path = "../rspack_error" }
