[package]
description = "rspack preact refresh loader"
edition     = "2021"
license     = "MIT"
name        = "rspack_loader_preact_refresh"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait          = { workspace = true }
rspack_cacheable     = { workspace = true }
rspack_core          = { workspace = true }
rspack_error         = { workspace = true }
rspack_hook          = { workspace = true }
rspack_loader_runner = { workspace = true }
