[package]
name = "rspack_css_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.34"
rspack_core = { path = "../rspack_core" }
rspack_style = "0.1.2"
tokio = { version = "1.17.0", features = ["full"] }
async-trait = "0.1.53"
