[package]
description       = "rspack benchmark tooling"
edition.workspace = true
license           = "MIT"
name              = "rspack_benchmark"
publish           = false
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[features]
codspeed = ["criterion2/codspeed"]
default  = []

[dependencies]
criterion2   = { workspace = true }
rspack       = { workspace = true, features = ["full"] }

[dev-dependencies]
# Make rust analyzer happy
rspack_cacheable = { workspace = true }
rspack_core = { workspace = true }
rspack_error = { workspace = true }
rspack_fs = { workspace = true }
rspack_regex = { workspace = true }
rspack_tasks = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[[bench]]
harness = false
name    = "benches"

[package.metadata.cargo-shear]
ignored = ["rspack_cacheable"]

[lints]
workspace = true
