
[package]
description       = "rspack macros test"
edition.workspace = true
license           = "MIT"
name              = "rspack_macros_test"
publish           = false
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[dev-dependencies]
async-trait        = { workspace = true }
rspack_cacheable   = { workspace = true }
rspack_collections = { workspace = true }
rspack_core        = { workspace = true }
rspack_error       = { workspace = true }
rspack_hash        = { workspace = true }
rspack_hook        = { workspace = true }
rspack_macros      = { workspace = true }
rspack_util        = { workspace = true }
tokio              = { workspace = true, features = ["macros"] }
tracing            = { workspace = true }
trybuild           = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing", "rspack_cacheable", "async-trait", "rspack_hash", "tokio"]

[lints]
workspace = true
