name: Single Docker build

description: Docker build for a single target

inputs:
  target:
    required: true
    type: string
  image:
    required: true
    type: string
  profile:
    default: 'release'
    required: false
    type: string
  options:
    description: 'Options for docker'
    default: ''
    required: false
    type: string
  pre:
    required: false
    default: ''
    type: string
  post:
    required: false
    default: ''
    type: string
  plugin:
    required: false
    default: true
    type: boolean

runs:
  using: composite
  steps:
    - name: Docker Build ${{ inputs.target }}
      uses: ./.github/actions/docker/run
      with:
        image: ${{ inputs.image }}
        script: |
          set -e
          ${{ inputs.pre }}
          rustup target add ${{ inputs.target }}

          npm install -g corepack@0.31.0 --force
          echo "Corepack version: $(corepack --version)"
          corepack enable

          RUST_TARGET=${{ inputs.target }} ${{ inputs.plugin == 'false' && 'DISABLE_PLUGIN=1' || '' }} pnpm build:binding:${{ inputs.profile }}
          ${{ inputs.post }}
        options: |
          -e CARGO_INCREMENTAL=0 \
          -v ~/.cargo:/usr/local/cargo \
          -v ~/.rustup:/usr/local/rustup \
          ${{ inputs.options }} \

    - name: Fix Permission
      run: sudo chown -R $USER:$USER ~/.cargo ~/.rustup ./target
      shell: bash
