[package]
name = "rspack"
version = "0.0.1"
edition = "2021"
description = "rich speedy pack"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sugar_path="0.0.4"
anyhow = "1"
crossbeam = "0.8.1"
dashmap = "5.0.0"
ena = "0.14.0"
env_logger = "0.9"
log = "0.4"
num_cpus = "1.13.1"
once_cell = "1"
petgraph = "0.6.0"
rayon = "1.5.1"
regex = "1.5.4"
smol_str = "0.1.21"
swc_atoms = "0.2.11"
swc_ecma_ast = "0.73.0"
swc_ecma_codegen = "0.101.0"
swc_ecma_parser = "0.98.1"
swc_ecma_visit = "0.59.0"
swc_common = "0.17.19"         # Common utilities for the swc project.
tokio = { version = "1.17.0", features = ["full"] }
async-trait = "0.1.53"
futures = "0.3.21"
swc = "0.161.1"
tracing = "0.1.32"
tracing-chrome = "0.4.0"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
linked-hash-map = "0.5.4"
nodejs_path = "=0.0.8"


[[examples]]
name="build"