[package]
edition = "2021"
name = "rspack"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev_dependencies]
criterion = {version = "0.3.6", features = ["async_tokio", "async_futures"]}
node_binding = {path = "../node_binding", package = "rspack_node", features = [
  "test",
]}
rspack_test = {path = "../rspack_test"}

[dependencies]
crossbeam = "0.8.1"
dashmap = "5.0.0"
rspack_core = {path = "../rspack_core"}
rspack_plugin_asset = {path = "../rspack_plugin_asset"}
rspack_plugin_css = {path = "../rspack_plugin_css"}
rspack_plugin_javascript = {path = "../rspack_plugin_javascript"}
rspack_plugin_json = {path = "../rspack_plugin_json"}
rspack_plugin_runtime = {path = "../rspack_plugin_runtime"}
# futures = "0.3.21"
anyhow = "1"
async-trait = "0.1.53"
nodejs-resolver = "0.0.14"
once_cell = "1"
sugar_path = "0.0.5"
tokio = {version = "1.17.0", features = ["full"]}
tracing = "0.1.34"
warp = "0.3"
# rspack_sources = "0.0.3"
hashbrown = {version = "0.12.1", features = ["rayon"]}
tracing-subscriber = {version = "0.3.9", features = ["env-filter"]}

[[bench]]
harness = false
hashbrown = {version = "0.12.1", features = ["rayon"]}
name = "main"
tracing-subscriber = {version = "0.3.9", features = ["env-filter"]}
