[package]
description = "rspack loader runner"
edition     = "2021"
license     = "MIT"
name        = "rspack_loader_runner"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
[dependencies]
anymap      = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true, features = ["debug"] }
rustc-hash  = { workspace = true }
tokio       = { workspace = true, features = ["test-util"] }

once_cell          = { workspace = true }
regex              = { workspace = true }
rspack_cacheable   = { workspace = true }
rspack_collections = { workspace = true }
rspack_error       = { workspace = true }
rspack_fs          = { workspace = true }
rspack_paths       = { workspace = true }
rspack_sources     = { workspace = true }
rspack_util        = { workspace = true }
serde_json         = { workspace = true }
tracing            = { workspace = true }
