[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_loader_runner"
repository = "https://github.com/web-infra-dev/rspack"
version    = "0.1.0"
description = "rspack loader runner"
[dependencies]
anymap      = { workspace = true }
async-trait = { workspace = true }
derivative  = { workspace = true }
rustc-hash  = { workspace = true }
tokio       = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "test-util", "parking_lot", "fs"] }

once_cell          = { workspace = true }
regex              = { workspace = true }
rspack_collections = { path = "../rspack_collections" }
rspack_error       = { path = "../rspack_error" }
rspack_sources     = { workspace = true }
rspack_util        = { path = "../rspack_util" }
serde_json         = { workspace = true }
