[package]
description = "rspack real_content_hash plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_real_content_hash"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap      = { workspace = true }
derive_more  = { workspace = true, features = ["debug"] }
indexmap     = { workspace = true }
once_cell    = { workspace = true }
rayon        = { workspace = true }
regex        = { workspace = true }
rspack_core  = { workspace = true }
rspack_error = { workspace = true }
rspack_hash  = { workspace = true }
rspack_hook  = { workspace = true }
rspack_util  = { workspace = true }
rustc-hash   = { workspace = true }
tracing      = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
