name: Run Script In Docker

description: run script in docker

inputs:
  image:
    required: true
    type: string
  options:
    description: 'Options for docker'
    default: ''
    required: false
    type: string
  script:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup dockerd, if needed
      if: runner.os != 'Windows'
      shell: bash
      run: |
        docker ps || nohup sudo dockerd >/dev/null 2>&1 &

    - name: Docker Build ${{ inputs.target }}
      shell: bash
      run: |
        code='${{ inputs.script }}'
        docker run \
          --network=host \
          --rm \
          --privileged \
          --user 0:0 \
          ${{ inputs.options }} \
          -e CI=1 \
          -v ${{ github.workspace }}:/rspack \
          -w /rspack \
          -i \
          ${{ inputs.image }} \
          bash -c "$code"
