[package]
description = "rspack entry plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_entry"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait  = { workspace = true }
rspack_core  = { workspace = true }
rspack_error = { workspace = true }
rspack_hook  = { workspace = true }
tracing      = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
