[package]
description       = "rspack watcher"
edition.workspace = true
license           = "MIT"
name              = "rspack_watcher"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[dependencies]
cow-utils    = { workspace = true }
dashmap      = { workspace = true }
fast-glob    = { workspace = true }
notify       = { workspace = true, features = ["macos_fsevent"] }
rspack_error = { workspace = true }
rspack_paths = { workspace = true }
rspack_regex = { workspace = true }
rspack_util  = { workspace = true }
tokio        = { workspace = true, features = ["rt", "macros", "sync", "time"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["rt", "macros", "sync", "fs"] }

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true
