[package]
description       = "Rslib native plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_rslib"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspack_cacheable         = { workspace = true }
rspack_core              = { workspace = true }
rspack_error             = { workspace = true }
rspack_hook              = { workspace = true }
rspack_plugin_javascript = { workspace = true }

serde_json = { workspace = true }
swc_core   = { workspace = true }
tracing    = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
