[package]
description        = "rspack dynamic entry plugin"
edition            = "2021"
homepage.workspace = true
license            = "MIT"
name               = "rspack_plugin_dll"
repository         = "https://github.com/web-infra-dev/rspack"
version            = "0.2.0"

[dependencies]
rspack_cacheable        = { workspace = true }
rspack_collections      = { workspace = true }
rspack_core             = { workspace = true }
rspack_error            = { workspace = true }
rspack_hook             = { workspace = true }
rspack_paths            = { workspace = true }
rspack_plugin_externals = { workspace = true }
rspack_util             = { workspace = true }

async-trait = { workspace = true }
rustc-hash  = { workspace = true }
serde       = { workspace = true, features = ["derive"] }
serde_json  = { workspace = true }
tracing     = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-shear]
ignored = ["tracing"]
