[package]
authors.workspace       = true
categories.workspace    = true
description             = "check whether crates missing field for publish"
documentation.workspace = true
edition                 = "2021"
homepage.workspace      = true
license.workspace       = true
name                    = "release-check"
repository.workspace    = true
version                 = "0.1.0"

[dependencies]
miette    = { version = "7.2.0", features = ["fancy"] }
thiserror = "2.0.12"
toml      = { version = "0.8.19" }

[lints]
workspace = true
