[package]
description       = "babel-plugin-import rewritten in Rust"
edition.workspace = true
license           = "MIT"
name              = "rspack_swc_plugin_import"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[dependencies]
cow-utils  = { workspace = true }
heck       = { workspace = true }
rustc-hash = { workspace = true }
serde      = { workspace = true }
swc_core   = { workspace = true, features = ["common", "ecma_ast", "ecma_visit"] }

[package.metadata.cargo-machete]
ignored = ["Inflector"]

[lints]
workspace = true
