[package]
description = "babel-plugin-import rewritten in Rust"
edition     = "2021"
license     = "MIT"
name        = "rspack_swc_plugin_import"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"

[dependencies]
cow-utils  = { workspace = true }
handlebars = "6.3.0"
heck       = { workspace = true }
rustc-hash = { workspace = true }
serde      = { workspace = true }
swc_core   = { workspace = true, features = ["common", "ecma_ast", "ecma_visit"] }

[package.metadata.cargo-machete]
ignored = ["Inflector"]
