[package]
description = "babel-plugin-import rewritten in Rust"
edition     = "2021"
license     = "MIT"
name        = "swc_plugin_import"
version     = "0.1.5"

[dependencies]
handlebars = "5.1.0"
heck       = { workspace = true }
rustc-hash = { workspace = true }
serde      = { workspace = true }
swc_core   = { workspace = true, features = ["common", "ecma_ast", "ecma_visit"] }

[package.metadata.cargo-machete]
ignored = ["Inflector"]
