[package]
description = "rspack hook"
edition     = "2021"
license     = "MIT"
name        = "rspack_hook"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait         = { workspace = true }
futures-concurrency = "7.6.2"
rspack_error        = { workspace = true }
rspack_macros       = { workspace = true }
rustc-hash          = { workspace = true }
