[package]
description       = "rspack hook"
edition.workspace = true
license           = "MIT"
name              = "rspack_hook"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait   = { workspace = true }
rspack_error  = { workspace = true }
rspack_macros = { workspace = true }
rustc-hash    = { workspace = true }
tracing       = { workspace = true }

[lints]
workspace = true
