[package]
description       = "rspack error"
edition.workspace = true
license           = "MIT"
name              = "rspack_error"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow             = { workspace = true, features = ["backtrace"] }
miette             = { workspace = true, features = ["fancy", "derive"] }
owo-colors         = { workspace = true }
rspack_cacheable   = { workspace = true }
rspack_collections = { workspace = true }
rspack_location    = { workspace = true }
rspack_paths       = { workspace = true }
serde_json         = { workspace = true }
termcolor          = { workspace = true }
textwrap           = { workspace = true }

unicode-width = { workspace = true }
