[package]
name = "rspack_error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
codespan-reporting = "0.11.1"
thiserror = "1.0.32"
