[package]
name = "rspack_style_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspack_core = { path = "../rspack_core" }
async-trait = "0.1.53"
