[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_plugin_asset"
repository = "https://github.com/modern-js-dev/rspack"
version    = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rspack_testing = { path = "../rspack_testing" }

[dependencies]
anyhow = "1"
async-trait = "0.1.53"
base64 = "0.13.0"
dashmap = "5.4.0"
mime_guess = "2.0.4"
once_cell = "1"
rayon = "1.5.3"
rspack_core = { path = "../rspack_core" }
rspack_error = { path = "../rspack_error" }
rspack_identifier = { path = "../rspack_identifier" }
serde_json = "1.0.91"
sugar_path = "0.0.9"
tokio = { version = "1.21.0", features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "test-util",
  "parking_lot",
] }
tracing = "0.1.34"
