[package]
edition = "2021"
name    = "rspack_plugin_html"
version = "0.1.0"

[dev-dependencies]
rspack_test = { path = "../rspack_test" }

[dependencies]
anyhow            = "1"
async-trait       = "0.1.53"
base64            = "0.13.0"
dojang            = "0.1.6"
hashbrown         = "0.12.1"
itertools         = "0.10.1"
once_cell         = "1"
rayon             = "1.5.3"
rspack_core       = { path = "../rspack_core" }
rspack_error      = { path = "../rspack_error" }
serde             = { version = "1", features = ["derive"] }
serde_json        = "1"
sha2              = "0.10.2"
sugar_path        = "0.0.8"
swc_core          = { workspace = true }
swc_html          = { workspace = true }
swc_html_minifier = { workspace = true }
