[package]
description = "rspack html plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_html"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.1.0"
[features]
default = []
testing = ["dep:schemars"]

[dependencies]
anyhow            = { workspace = true }
itertools         = { workspace = true }
path-clean        = { workspace = true }
rayon             = { workspace = true }
regex             = { workspace = true }
rspack_base64     = { version = "0.1.0", path = "../rspack_base64" }
rspack_core       = { version = "0.1.0", path = "../rspack_core" }
rspack_dojang     = "0.1.7"
rspack_error      = { version = "0.1.0", path = "../rspack_error" }
rspack_hook       = { version = "0.1.0", path = "../rspack_hook" }
rspack_paths      = { version = "0.1.0", path = "../rspack_paths" }
rspack_util       = { version = "0.1.0", path = "../rspack_util" }
schemars          = { workspace = true, optional = true }
serde             = { workspace = true, features = ["derive"] }
serde_json        = { workspace = true }
sha2              = "0.10.8"
sugar_path        = { workspace = true }
swc_core          = { workspace = true }
swc_html          = { workspace = true }
swc_html_minifier = { workspace = true, features = ["custom-css-minifier"] }
tracing           = { workspace = true }
urlencoding       = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
