[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_glob"
repository = "https://github.com/web-infra-dev/rspack"
version    = "0.1.0"

[dependencies]
fast-glob = { workspace = true }
