[package]
description       = "rspack tracing"
edition.workspace = true
license           = "MIT"
name              = "rspack_tracing"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rspack_tracing_perfetto = { workspace = true }
serde_json              = { workspace = true }
tracing-subscriber      = { workspace = true, features = ["env-filter", "json"] }
