[package]
description       = "rspack benchmark tooling"
edition.workspace = true
license           = "MIT"
name              = "rspack_benchmark"
publish           = false
repository        = "https://github.com/web-infra-dev/rspack"
version           = "0.2.0"

[features]
codspeed = ["criterion2/codspeed"]
default  = []

[dependencies]
criterion2   = { default-features = false, version = "2.0.0", features = ["async_tokio"] }
rspack       = { workspace = true, features = ["full"] }
rspack_core  = { workspace = true }
rspack_fs    = { workspace = true }
rspack_regex = { workspace = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }

[dev-dependencies]
# Make rust analyzer happy
rspack_cacheable = { workspace = true }

[[bench]]
harness = false
name    = "benches"

[package.metadata.cargo-shear]
ignored = ["rspack_cacheable"]
