[package]
description       = "rspack copy plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_copy"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
[dependencies]
dashmap      = { workspace = true }
derive_more  = { workspace = true, features = ["debug"] }
futures      = { workspace = true }
glob         = { workspace = true }
pathdiff     = { workspace = true, features = ["camino"] }
regex        = { workspace = true }
rspack_core  = { workspace = true }
rspack_error = { workspace = true }
rspack_hash  = { workspace = true }
rspack_hook  = { workspace = true }
rspack_paths = { workspace = true }
rustc-hash   = { workspace = true }
sugar_path   = { workspace = true }
tracing      = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]

[lints]
workspace = true
