[package]
description = "rspack copy plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_copy"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.1.0"
[dependencies]
dashmap        = { workspace = true }
derivative     = { workspace = true }
futures        = { workspace = true }
glob           = { workspace = true }
lazy_static    = "1.4.0"
pathdiff       = { workspace = true }
regex          = { workspace = true }
rspack_core    = { version = "0.1.0", path = "../rspack_core" }
rspack_error   = { version = "0.1.0", path = "../rspack_error" }
rspack_futures = { version = "0.1.0", path = "../rspack_futures" }
rspack_hash    = { version = "0.1.0", path = "../rspack_hash" }
rspack_hook    = { version = "0.1.0", path = "../rspack_hook" }
rspack_util    = { version = "0.1.0", path = "../rspack_util" }
rustc-hash     = { workspace = true }
sugar_path     = { workspace = true }
tokio          = { workspace = true, features = ["fs"] }
tracing        = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
