[package]
description = "rspack copy plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_copy"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
[dependencies]
dashmap        = { workspace = true }
derive_more    = { workspace = true, features = ["debug"] }
futures        = { workspace = true }
glob           = { workspace = true }
pathdiff       = { workspace = true, features = ["camino"] }
regex          = { workspace = true }
rspack_core    = { workspace = true }
rspack_error   = { workspace = true }
rspack_futures = { workspace = true }
rspack_hash    = { workspace = true }
rspack_hook    = { workspace = true }
rspack_paths   = { workspace = true }
rspack_util    = { workspace = true }
rustc-hash     = { workspace = true }
sugar_path     = { workspace = true }
tracing        = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["fs"] }

[package.metadata.cargo-shear]
ignored = ["tracing"]
