[package]
description = "rspack extract css plugin"
edition     = "2021"
license     = "MIT"
name        = "rspack_plugin_extract_css"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"
[dependencies]
async-trait              = { workspace = true }
cow-utils                = { workspace = true }
regex                    = { workspace = true }
rspack_cacheable         = { workspace = true }
rspack_collections       = { workspace = true }
rspack_core              = { workspace = true }
rspack_error             = { workspace = true }
rspack_hash              = { workspace = true }
rspack_hook              = { workspace = true }
rspack_paths             = { workspace = true }
rspack_plugin_css        = { workspace = true }
rspack_plugin_javascript = { workspace = true }
rspack_plugin_runtime    = { workspace = true }
rspack_util              = { workspace = true }
rustc-hash               = { workspace = true }
serde                    = { workspace = true, features = ["derive"] }
serde_json               = { workspace = true }
tracing                  = { workspace = true }
ustr                     = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
