[package]
description       = "rspack subresource integrity plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_sri"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait                     = { workspace = true }
cow-utils                       = { workspace = true }
derive_more                     = { workspace = true, features = ["debug"] }
futures                         = { workspace = true }
indexmap                        = { workspace = true }
once_cell                       = { workspace = true }
pathdiff                        = { workspace = true }
rayon                           = { workspace = true }
regex                           = { workspace = true }
rspack_cacheable                = { workspace = true }
rspack_collections              = { workspace = true }
rspack_core                     = { workspace = true }
rspack_error                    = { workspace = true }
rspack_fs                       = { workspace = true }
rspack_hash                     = { workspace = true }
rspack_hook                     = { workspace = true }
rspack_paths                    = { workspace = true }
rspack_plugin_html              = { workspace = true }
rspack_plugin_real_content_hash = { workspace = true }
rspack_plugin_runtime           = { workspace = true }
rspack_util                     = { workspace = true }
rustc-hash                      = { workspace = true }
serde_json                      = { workspace = true }
sha2                            = { workspace = true }
tokio                           = { workspace = true }
tracing                         = { workspace = true }
url                             = { workspace = true }
urlencoding                     = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing", "async-trait", "rspack_hash", "tokio"]

[lints]
workspace = true
