[package]
edition = "2021"
name    = "rspack_database"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
rayon = ["dep:rayon"]

[dependencies]
dashmap    = "5.4.0"
once_cell  = "1.17.0"
rustc-hash = { workspace = true }

  [dependencies.rayon]
  optional = true
  version  = "1.5.3"
