[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_base64"
repository = "https://github.com/web-infra-dev/rspack"
version    = "0.1.0"


[dependencies]
base64-simd = { version = "0.8.0", features = ["alloc"] }
