[package]
description = "rspack id implementation"
edition     = "2021"
license     = "MIT"
name        = "rspack_ids"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools    = { workspace = true }
rayon        = { workspace = true }
regex        = { workspace = true }
rspack_core  = { version = "0.1.0", path = "../rspack_core" }
rspack_error = { version = "0.1.0", path = "../rspack_error" }
rspack_hook  = { version = "0.1.0", path = "../rspack_hook" }
rspack_util  = { version = "0.1.0", path = "../rspack_util" }
tracing      = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
