[package]
description       = "rspack location"
edition.workspace = true
license           = "MIT"
name              = "rspack_location"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[dependencies]
itoa             = { workspace = true }
rspack_cacheable = { workspace = true }
swc_core         = { workspace = true, features = ["common"] }
