name: Benchmark History
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  repository-projects: write

jobs:
  benchmark:
    name: Run Criterion.rs benchmark
    runs-on: [self-hosted, rspack-bench]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install toolchain
        run: rustup show
      - name: Run benchmark
        run: |
          set -o pipefail 
          cargo bench --bench main -- --output-format bencher | tee output.txt
          pnpm i
          ./x build cli:release
          export ROOT_DIR=$(pwd) && cd benchcases/react-refresh && pnpm dev

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1.14.0
        with:
          name: Rust Benchmark
          tool: "cargo"
          output-file-path: output.txt
          github-token: ${{ secrets.PR_STATS_COMMENT_TOKEN }}
          auto-push: true
          gh-repository: "github.com/speedy-js/metrics"

          # Show alert with commit comment on detecting possible performance regression
          fail-on-alert: false

      # - name: Push benchmark result
      #   run: git push 'https:///speedy-js:${{ secrets.GITHUB_TOKEN }}@github.com/speedy-js/rspack.git' gh-pages:gh-pages
