name: check

on:
  push:
    branches:
      - main
      - next
    tags-ignore:
      - "**"
  pull_request:

env:
  TRACE: DEBUG

jobs:
  format:
    name: Format Rust Files
    runs-on: [self-hosted, rspack-common]
    steps:
      - name: Cleanup workspace
        uses: TooMuch4U/actions-clean@v2.1
        if: ${{ always() }}
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Support longpaths
        run: git config core.longpaths true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup show
      #- name: Cache
      #uses: speedy-js/rust-cache-self-hosted@v1
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --verbose -- --check

  lint:
    name: Lint Rust Files
    runs-on: [self-hosted, rspack-common]
    steps:
      - name: Cleanup workspace
        uses: TooMuch4U/actions-clean@v2.1
        if: ${{ always() }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install toolchain
        run: rustup show
      #- name: Cache
      # uses: speedy-js/rust-cache-self-hosted@v1
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets --verbose -- --deny warnings

  test-rs:
    name: Rust test
    strategy:
      fail-fast: true
    runs-on: [self-hosted, rspack-common]
    timeout-minutes: 30
    steps:
      - name: Cleanup workspace
        uses: TooMuch4U/actions-clean@v2.1
        if: ${{ always() }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install toolchain
        run: rustup show
      - name: Run test
        run: cargo test --all -- --nocapture
  test-js:
    name: Node binding test
    runs-on: [self-hosted, rspack-common]
    steps:
      - name: Cleanup workspace
        uses: TooMuch4U/actions-clean@v2.1
        if: ${{ always() }}
      - name: Run test
        run: |
          yarn install --no-immutable
          yarn workspace @rspack/binding run build
          yarn workspace rspack-dev-server run build
          yarn workspace @rspack/core run build
          yarn workspace @rspack/core run example
      #- name: Cache
      #uses: speedy-js/rust-cache-self-hosted@v1
      # - name: Install yarn
      #   run: npm install -g yarn
      # - name: yarn install --no-immutable
      #   run: npm run init
      # - name: Configure cache
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: test-${{ runner.os }}-cargo-gcc-${{ matrix.gcc }}-clang-${{ matrix.clang }}-${{ hashFiles('**/Cargo.lock') }}
      run: |
        pnpm install
        pnpm --filter @rspack/binding run build 
        pnpm --filter rspack-dev-server run build 
        pnpm --filter @rspack/core run build 
        pnpm --filter @rspack/core run example
