name: check

on:
  push:
    branches:
      - main
      - next
    tags-ignore:
      - "**"
  pull_request:

# env:
#   TRACE: DEBUG

jobs:
  format:
    name: Format Rust Files
    runs-on: [self-hosted, rspack-common]
    steps:
      # - name: Cleanup workspace
      #   uses: TooMuch4U/actions-clean@v2.1
      #   if: ${{ always() }}
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Support longpaths
        run: git config core.longpaths true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup show
      #- name: Cache
      #uses: speedy-js/rust-cache-self-hosted@v1
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --verbose -- --check

  lint:
    name: Lint Rust Files
    runs-on: [self-hosted, rspack-common]
    steps:
      # - name: Cleanup workspace
      #   uses: TooMuch4U/actions-clean@v2.1
      #   if: ${{ always() }}
      - name: Checkout repository
        uses: actions/checkout@v3
        # - name: Install protoc
        #   uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install toolchain
        run: rustup show
      #- name: Cache
      # uses: speedy-js/rust-cache-self-hosted@v1
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets --verbose -- --deny warnings
      - name: Check Dependencies
        run: |
          node ./scripts/check_rust_dependency.js

  test-rs:
    name: Rust test
    strategy:
      fail-fast: true
    runs-on: [self-hosted, rspack-common]
    timeout-minutes: 30
    steps:
      # - name: Cleanup workspace
      #   uses: TooMuch4U/actions-clean@v2.1
      #   if: ${{ always() }}
      - name: Checkout repository
        uses: actions/checkout@v3
        # - name: Install protoc
        #   uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          architecture: "arm64"
      - name: Install toolchain
        run: rustup show
      - name: Run test
        # We need to install sass first to enable sass-loader
        run: |
          pnpm i
          cargo test --all -- --nocapture

  test-js:
    name: Node binding test
    runs-on: [self-hosted, rspack-common]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # - name: Install protoc
        #   uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          architecture: "arm64"
      - name: Install dependencies && and build lib
        run: |
          pnpm install
          pnpm run lint:js
          pnpm run build:cli
      - name: binding test
        run: |
          pnpm --filter @rspack/core run test
          pnpm run build:webpack
      #- name: Cache
      #uses: speedy-js/rust-cache-self-hosted@v1
      # - name: Install yarn
      #   run: npm install -g yarn
      # - name: yarn install --no-immutable
      #   run: npm run init
      # - name: Configure cache
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: test-${{ runner.os }}-cargo-gcc-${{ matrix.gcc }}-clang-${{ matrix.clang }}-${{ hashFiles('**/Cargo.lock') }}
