# Diff assets comment with "!diff"

name: Diff Assets

on:
  issue_comment:
    types: [created]

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  build:
    name: Build
    needs: [get-runner-labels]
    if: github.event.issue.pull_request && contains(github.event.comment.body, '!diff')
    strategy:
      fail-fast: false # Build and test everything so we can look at all the errors
      matrix:
        array:
          - target: x86_64-unknown-linux-gnu # For Cloud IDE
            runner: ${{ needs.get-runner-labels.outputs.LINUX_RUNNER_LABELS }}
    uses: ./.github/workflows/reusable-build.yml
    with:
      ref: refs/pull/${{ github.event.issue.number }}/head
      target: ${{ matrix.array.target }}
      runner: ${{ matrix.array.runner }}
      test: false

  diff:
    name: Diff Assets
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Pnpm Cache
        uses: ./.github/actions/pnpm-cache

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Build node packages
        run: pnpm run build:js

      - name: Move artifacts
        run: node scripts/build-npm.cjs

      - name: Build Viewer
        run: pnpm run build:viewer

      - name: Run Diff
        run: node scripts/diff.cjs

      - name: Upload Diff Report
        id: upload-artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: diff-report
          path: diff_output
          try-local-cache: false
          mv-when-local: false
      
      - name: Write a new comment
        uses: peter-evans/create-or-update-comment@v3
        continue-on-error: true
        with:
          issue-number: ${{ github.event.issue.number }}
          body-path: 'diff_output/stats.md'
