# Origin Source
# https://github.com/ant-design/ant-design/blob/79f566b7f8abb1012ef55b0d2793bfdf5595b85d/.github/workflows/issue-reply.yml
name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  contents: read
  # for `actions-cool/issues-helper` to update issues
  issues: write
  # for `actions-cool/issues-helper` to update PRs
  pull-requests: write

jobs:
  issue-labeled:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: ðŸ¤” Need Reproduce
        if: github.event.label.name == 'need reproduction'
        uses: actions-cool/issues-helper@d1d51fccf39469b5458203b1369060db0ff0c0db # v3.7.4
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, sorry we can't investigate the problem further without reproduction demo, please provide a repro demo by forking [rspack-repro](https://github.com/web-infra-dev/rspack-repro), or provide a minimal GitHub repository by yourself. Issues labeled by `need reproduction` will be closed if no activities in 14 days.
      - name: invalid
        if: github.event.label.name == 'invalid'
        uses: actions-cool/issues-helper@d1d51fccf39469b5458203b1369060db0ff0c0db # v3.7.4
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not conform to our issue requirements. Please use our [issue template](https://github.com/web-infra-dev/rspack/issues/new/choose) to create an issue, thank you!
