name: PR Labeler

on:
  pull_request_target:
    types:
      - opened
      - edited

permissions:
  # Allow `github/issue-labeler` to add labels
  issues: write
  pull-requests: write

jobs:
  release-labeling:
    # See context at https://github.com/web-infra-dev/rspack/discussions/2760
    name: Labeling for releasing
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/pr-labeler.yml
          enable-versioned-regex: 0
          include-title: 1
          sync-labels: 1
