name: Release Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Release Version(major|minor|patch|snapshot)"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch
          - snapshot
  schedule:
    # 08:00 AM Beijing Time on every Tuesday
    - cron: "0 0 * * 2"

jobs:
  release:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    if: github.repository_owner == 'web-infra-dev'

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pnpm Cache
        uses: ./.github/actions/pnpm-cache

      - name: Create Release Pull Request
        uses: hardfist/rspack-action@rspack
        with:
          version: node ./x version ${{inputs.version || 'patch'}}
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
