name: Release Debug

on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
        type: string
        description: "Commit SHA"
  workflow_run:
    workflows: ["Release Full"]
    types:
      - completed
permissions:
  # To publish packages with provenance
  id-token: write
  # Allow commenting on issues for `reusable-build.yml`
  issues: write

jobs:
  build:
    name: Build All Debug Bindings
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable-build-all.yml
    with:
      ref: ${{inputs.commit || github.event.workflow_run.head_sha }}
      profile: debug

  release:
    name: Release Debug
    runs-on: ubuntu-latest
    needs: build
    environment: npm-canary
    steps:
      - name: Checkout Branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 1
          ref: ${{inputs.commit || github.event.workflow_run.head_sha }}

      - name: Pnpm Setup
        uses: ./.github/actions/pnpm/setup

      - name: Pnpm Install
        uses: ./.github/actions/pnpm/install-dependencies

      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: artifacts

      - name: Clean artifacts
        run: find artifacts -type f -name '*.d.ts'  | xargs rm -f

      - name: Move artifacts
        run: node scripts/build-npm.cjs

      - name: Show binding packages
        run: ls -R npm

      - name: Resolve dependencies for bindings
        run: pnpm install --no-frozen-lockfile

      # Update npm to the latest version to enable OIDC
      - name: Update npm
        run: |
          npm install -g npm@latest
          npm --version

      - name: Release Debug
        run: |
          pnpm run build:js
          ./x version debug
          ./x publish stable --tag latest
