name: Release Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Release Version (major|minor|patch|snapshot)"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch
          - snapshot
      prerelease:
        type: choice
        description: "Pre Release Tag (alpha|beta|rc)"
        required: true
        default: "none"
        options:
          - none
          - alpha
          - beta
          - rc

  schedule:
    # 08:00 AM Beijing Time on every Tuesday
    - cron: "0 0 * * 2"

jobs:
  release:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    if: github.repository_owner == 'web-infra-dev'

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Pnpm Cache
        uses: ./.github/actions/pnpm-cache

      - name: Create Release Pull Request
        # https://github.com/rspack-contrib/rspack-action
        uses: rspack-contrib/rspack-action@rspack
        with:
          version: node ./x version ${{inputs.version || 'patch'}} --pre ${{inputs.prerelease || 'none'}}
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
