[package]
description       = "rspack web worker plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_web_worker_template"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspack_core           = { workspace = true }
rspack_plugin_runtime = { workspace = true }

[lints]
workspace = true
