[package]
description = "rspack regex"
edition     = "2021"
license     = "MIT"
name        = "rspack_regex"
repository  = "https://github.com/web-infra-dev/rspack"
version     = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cow-utils        = { workspace = true }
napi             = { workspace = true }
regex-syntax     = { version = "0.8.5", default-features = false, features = ["std"] }
regress          = "0.10.1"
rspack_cacheable = { workspace = true }
rspack_error     = { workspace = true }
swc_core         = { workspace = true, features = ["ecma_ast"] }

[dev-dependencies]
swc_core = { workspace = true, features = [
  "ecma_ast",
  "__visit",
  "__common",
  "__parser",
  "__utils",
  "ecma_preset_env",
] }
