[package]
description       = "rspack regex"
edition.workspace = true
license           = "MIT"
name              = "rspack_regex"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cow-utils        = { workspace = true }
napi             = { workspace = true }
regex            = { workspace = true }
regex-syntax     = { workspace = true }
regress          = { workspace = true, features = ["backend-pikevm", "std"] }
rspack_cacheable = { workspace = true }
rspack_error     = { workspace = true }
swc_core         = { workspace = true, features = ["ecma_ast"] }

[dev-dependencies]
swc_core = { workspace = true, features = [
  "ecma_ast",
  "__visit",
  "__common",
  "__parser",
  "__utils",
  "ecma_preset_env",
] }

[lints]
workspace = true
