[package]
edition    = "2021"
license    = "MIT"
name       = "rspack_regex"
repository = "https://github.com/web-infra-dev/rspack"
version    = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-syntax = { version = "0.8.3", default-features = false, features = ["std"] }
regress      = "0.9.1"
rspack_error = { path = "../rspack_error" }
swc_core     = { workspace = true, features = ["ecma_ast"] }

[dev-dependencies]
swc_core = { workspace = true, features = [
  "ecma_ast",
  "__visit",
  "__common",
  "__parser",
  "__utils",
  "ecma_preset_env",
] }
