[package]
authors.workspace       = true
categories.workspace    = true
description             = "Rspack tracing perfetto"
documentation.workspace = true
edition.workspace       = true
homepage.workspace      = true
license.workspace       = true
name                    = "rspack_tracing_perfetto"
repository.workspace    = true
version.workspace       = true

[dependencies]
bytes               = { workspace = true }
micromegas-perfetto = { workspace = true }
prost               = { workspace = true }
tracing             = { workspace = true }
tracing-subscriber  = { workspace = true }
allocative          = { workspace = true, optional = true }

[lints]
workspace = true
