[package]
description       = "rspack circular dependency detection plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_circular_dependencies"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[dependencies]
cow-utils          = { workspace = true }
derive_more        = { workspace = true, features = ["debug"] }
futures            = { workspace = true }
itertools          = { workspace = true }
rspack_collections = { workspace = true }
rspack_core        = { workspace = true }
rspack_error       = { workspace = true }
rspack_hook        = { workspace = true }
rspack_regex       = { workspace = true }
rustc-hash         = { workspace = true }
tracing            = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]

[lints]
workspace = true
