[package]
description       = "rspack css chunking plugin"
edition.workspace = true
license           = "MIT"
name              = "rspack_plugin_css_chunking"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[dependencies]
indexmap           = { workspace = true }
rspack_collections = { workspace = true }
rspack_core        = { workspace = true }
rspack_error       = { workspace = true }
rspack_hook        = { workspace = true }
rspack_plugin_css  = { workspace = true }
rspack_regex       = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing", "tokio"]

[lints]
workspace = true
